# Generated by Django 5.0.2 on 2024-04-30 22:03

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about_us", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="PNG",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[900, 400],
                upload_to="about_us/post",
            ),
        ),
    ]
