# Generated by Django 5.0.2 on 2024-05-11 18:01

import blog.models
import django.contrib.auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_article_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET(blog.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
                verbose_name=django.contrib.auth.models.User,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET(blog.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
                verbose_name=django.contrib.auth.models.User,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET(blog.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
                verbose_name=django.contrib.auth.models.User,
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET(blog.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
                verbose_name=django.contrib.auth.models.User,
            ),
        ),
    ]
